### PR TITLE
Refactor rdf object loader to builder

### PR DESCRIPTION
**Pull request by ZacharyWhitley**

### CODE REVIEW

**Comment by pmaria** [comment]
Hi @ZacharyWhitley, thanks again for looking at this.

There are some problems here. There is a compilation error in carml-engine because of a visibility issue. And there are multiple Type safety related warnings. These would have to be fixed before a merge.

Looking at the issue again, I opened this because of the amount of parameters that were being passed to the load methods. But, due to the parameterized type being passed, I don't know if the builder pattern is the best option here. I would have to look into it more closely. I might have some time later this week.

Pano

**Comment by ZacharyWhitley** [comment]
Sorry about that. I don't recall seeing any build errors but I'll take a look at it. I agree that it makes for a somewhat awkward builder and that it might benefit from a larger refactoring but I'm not familiar enough to know what that might entail. It was a nice start to digging  into the code.

**Comment by ZacharyWhitley** [comment]
I fixed up the visibility issue. Don't know how I missed that so it at least compiles now. Still has the unchecked assignments that are going to be a little more difficult to eliminate. Like you said builder might not be the best fit here but you asked for a builder and you got a builder ;)

Let me know if there's anything else I can help out with.

**Comment by pmaria** [comment]
closing this, will reconsider during larger refactoring.

**Pull request closed without merging**
